const systemDictionary = {
    'Restarting...': {
        en: 'Restarting...',
        de: 'Bot wird neu gestartet.',
        ru: 'Перезапуск бота.',
        pt: 'O bot será reiniciado.',
        nl: 'Het opnieuw starten ...',
        fr: 'Redémarrer ...',
        it: 'Riavvio ...',
        es: 'Reiniciando ...',
        pl: 'Ponowne uruchamianie ...',
        uk: 'Перезавантаження...',
        'zh-cn': '正在重新启动...',
    },
    'Restarting... Reauthenticate!': {
        en: 'Restarting... Re-authenticate!',
        de: 'Neustart ... Erneut authentifizieren!',
        ru: 'Перезапуск ... Повторно аутентифицировать!',
        pt: 'Reiniciando... Autentique-se novamente!',
        nl: 'Opnieuw opstarten ... Opnieuw verifiëren!',
        fr: 'Redémarrer ... Ré-authentifier!',
        it: 'Riavvio ... Re-authenticate!',
        es: 'Reiniciando ... ¡Vuelve a autenticarte!',
        pl: 'Restartowanie ... Ponownie uwierzytelnij!',
        uk: 'Перезавантаження... Реабілітація!',
        'zh-cn': '正在重新启动...重新认证！',
    },
    'ON-Status': {
        en: 'switched on',
        de: 'eingeschaltet',
        ru: 'включен(о/а)',
        pt: 'ligado',
        nl: 'ON-Status',
        fr: 'ON-Status',
        it: 'ON-Stato',
        es: 'Estado de encendido',
        pl: 'ON-Status',
        uk: 'Оф-статус',
        'zh-cn': '切换到',
    },
    'OFF-Status': {
        en: 'switched off',
        de: 'ausgeschaltet',
        ru: 'выключен(о/а)',
        pt: 'apagado',
        nl: 'OFF-Status',
        fr: 'Statut OFF',
        it: 'OFF-Stato',
        es: 'Estado apagado',
        pl: 'OFF-Status',
        uk: 'Статус на сервери',
        'zh-cn': '关掉',
    },
    'Call text': {
        en: 'This is ioBroker calling. Something happened in your house.',
        de: 'Das ist ioBroker. Etwas ist in Ihrem Haus passiert.',
        ru: 'Это звонит ioBroker. Что-то случилось в вашем доме.',
        pt: 'Isto é ioBroker a ligar. Aconteceu alguma coisa na tua casa.',
        nl: 'Dit is ioBroker. Er is iets gebeurd in je huis.',
        fr: 'C\'est ioBroker qui appelle. Il s\'est passé quelque chose chez toi.',
        it: 'Questo è ioBroker che chiama. E\' successo qualcosa in casa tua.',
        es: 'Esto es ioBroker llamando. Algo pasó en tu casa.',
        pl: 'Tu JoBroker. Coś się stało w twoim domu.',
        uk: 'Це ioBroker виклик. Що сталося в будинку.',
        'zh-cn': '这是ioBroker呼叫。 你家里出了点事.',
    },
    'value as boolean': {
        en: 'value as boolean',
        de: 'Wert als Boolean',
        ru: 'логическое значение',
        pt: 'valor como booleano',
        nl: 'waarde als Boolean',
        fr: 'valeur en tant que booléen',
        it: 'valore come booleano',
        es: 'valor como booleano',
        pl: 'wartość jako boolean',
        uk: 'значення як boolean',
        'zh-cn': '布尔值',
    },
    'value as number': {
        en: 'value as number',
        de: 'Wert als Zahl',
        ru: 'значение в виде число',
        pt: 'valor como numero',
        nl: 'waarde als nummer',
        fr: 'valeur en nombre',
        it: 'valore come numero',
        es: 'valor como numero',
        pl: 'wartość jako liczba',
        uk: 'значення як номер',
        'zh-cn': '价值作为数字',
    },
    'value as string': {
        en: 'value as string',
        de: 'Wert als String',
        ru: 'значение в виде строки',
        pt: 'valor como string',
        nl: 'waarde als tekenreeks',
        fr: 'valeur sous forme de chaîne',
        it: 'valore come stringa',
        es: 'valor como cadena',
        pl: 'wartość jako ciąg',
        uk: 'значення як рядок',
        'zh-cn': '值作为字符串',
    },
    'Select option': {
        en: 'Select option',
        de: 'Wähle eine Option',
        ru: 'Выберите опцию',
        pt: 'Selecione uma opção',
        nl: 'Selecteer optie',
        fr: 'Sélectionnez une option',
        it: 'Selezionare l\'opzione',
        es: 'Seleccionar opción',
        pl: 'Wybierz opcję',
        uk: 'Виберіть опцію',
        'zh-cn': '选择选项',
    },
    'Message ignored: ': {
        en: 'Message ignored: ',
        de: 'Meldung wurde ignoriert: ',
        ru: 'Сообщение проигнорировано: ',
        pt: 'Mensagem foi ignorada: ',
        nl: 'Bericht genegeerd: ',
        fr: 'Message ignoré: ',
        it: 'Messaggio ignorato: ',
        es: 'Mensaje ignorado: ',
        pl: 'Wiadomość została zignorowana: ',
        uk: 'Повідомлення ігнорується: ',
        'zh-cn': '讯息被忽略：',
    },
    'Please enter password in form "/password phrase"': {
        en: 'Please enter password in form "/password phrase"',
        de: 'Das Password muss in der Form "/password phrase" eingegeben werden',
        ru: 'Пожалуйста введите пароль в формате: "/password phrase"',
        pt: 'A senha deve ser inserida no formato "/password phrase"',
        nl: 'Voer een wachtwoord in het formulier "/ wachtwoord zin"',
        fr: 'Veuillez entrer le mot de passe dans le formulaire "/mot de passe"',
        it: 'Per favore inserisci la password nel modulo "/ frase password"',
        es: 'Por favor, introduzca la contraseña en el formulario "/frase de contraseña"',
        pl: 'Proszę podać hasło w formularzu "/hasło zwrotne"',
        uk: 'Будь ласка, введіть пароль у форму "/password фраза"',
        'zh-cn': '请以“ /密码短语”形式输入密码',
    },
    'Too many attempts. Blocked for': {
        en: 'Too many attempts. Blocked for',
        de: 'Zu viele Versuche. Geblockt für',
        ru: 'Слишком много попыток. Заблокировано',
        pt: 'Muitas tentativas. Bloqueado para',
        nl: 'Te veel pogingen. Geblokkeerd voor',
        fr: 'Trop de tentatives. Bloqué pour',
        it: 'Troppi tentativi. Bloccato per',
        es: 'Demasiados intentos. Bloqueado para',
        pl: 'Zbyt wiele prób. Zablokowany',
        uk: 'Занадто багато спроб. Заблоковано',
        'zh-cn': '尝试太多。 屏蔽为',
    },
    'seconds': {
        en: 'seconds',
        de: 'Sekunden',
        ru: 'секунд',
        pt: 'segundos',
        nl: 'seconden',
        fr: 'secondes',
        it: 'secondi',
        es: 'segundos',
        pl: 'sekund',
        uk: 'час',
        'zh-cn': '秒数',
    },
    'Welcome ': {
        en: 'Welcome ',
        de: 'Hallo ',
        ru: 'Добро пожаловать ',
        pt: 'Oi ',
        nl: 'Welkom ',
        fr: 'Bienvenue ',
        it: 'benvenuto ',
        es: 'Bienvenido ',
        pl: 'Witamy ',
        uk: 'Про нас ',
        'zh-cn': '欢迎 ',
    },
    'Invalid password': {
        en: 'Invalid password!',
        de: 'Ungültiges Passwort!',
        ru: 'Неверный пароль!',
        pt: 'Senha inválida!',
        nl: 'Ongeldig wachtwoord!',
        fr: 'Mot de passe incorrect!',
        it: 'Password non valida!',
        es: '¡Contraseña invalida!',
        pl: 'Nieprawidłowe hasło!',
        uk: 'Ім\'я користувача!',
        'zh-cn': '无效的密码！',
    },
    'User is not in the list': {
        en: 'User is not in the list',
        de: 'Benutzer ist nicht in der Liste',
        ru: 'Пользователь не входит в список',
        pt: 'O usuário não está na lista',
        nl: 'Gebruiker staat niet in de lijst',
        fr: 'L\'utilisateur n\'est pas dans la liste',
        it: 'L\'utente non è nella lista',
        es: 'El usuario no está en la lista',
        pl: 'Użytkownik nie jest na liście',
        uk: 'Користувач не в списку',
        'zh-cn': '用户不在列表中',
    },
    'Invalid number %s': {
        en: 'Invalid number %s',
        de: 'Ungültige Nummer %s',
        ru: 'Неверное число %s',
        pt: 'Número inválido %s',
        nl: 'Ongeldig aantal %s',
        fr: 'Nombre invalide %s',
        it: 'Numero non valido %s',
        es: 'Número inválido %s',
        pl: 'Nieprawidłowy numer %s',
        uk: 'Неточна кількість %s',
        'zh-cn': '无效的号码％s',
    },
    'Done': {
        en: 'Done',
        de: 'Fertig',
        ru: 'Готово',
        pt: 'Pronto',
        nl: 'Gedaan',
        fr: 'Terminé',
        it: 'Fatto',
        es: 'Hecho',
        pl: 'Gotowe',
        uk: 'Сонце',
        'zh-cn': '完毕',
    },
    'ID "%s" not found.': {
        en: 'ID "%s" not found.',
        de: 'ID "%s" nicht gefunden.',
        ru: 'Идентификатор " %s" не найден.',
        pt: 'ID "%s" não foi encontrado.',
        nl: 'ID "%s" niet gevonden.',
        fr: 'ID "%s" non trouvé.',
        it: 'ID "%s" non trovato.',
        es: 'No se encontró el ID "%s".',
        pl: 'Nie znaleziono identyfikatora "%s".',
        uk: 'Не знайдено ID "%s".',
        'zh-cn': '找不到ID“％s”。',
    },
    'Started!': {
        en: 'Started!',
        de: 'Bot gestartet.',
        ru: 'Бот запущен!',
        pt: 'O bot foi iniciado!',
        nl: 'Begonnen!',
        fr: 'Commencé!',
        it: 'Iniziato!',
        es: '¡Empezado!',
        pl: 'Rozpoczęty!',
        uk: 'Почати!',
        'zh-cn': '开始！',
    },
};

module.exports = function (text, lang) {
    if (systemDictionary?.[text]) {
        return systemDictionary[text][lang] || systemDictionary[text].en || text;
    } else {
        return text;
    }
};
