/**
 * Voices the Telegram call block offers, as they come from the adapter.
 *
 * The first dropdown entry is not in here: "System language" is translated at runtime.
 */
export const CALL_VOICES: [string, string][] = [
    ['German (Germany) (Female)', 'de-DE-Standard-A'],
    ['German (Germany) (Male)', 'de-DE-Standard-B'],
    ['English (US) (Male)', 'en-US-Standard-B'],
    ['English (US) (Female)', 'en-US-Standard-C'],
    ['English (US) (Male 2)', 'en-US-Standard-D'],
    ['English (US) (Female 2)', 'en-US-Standard-E'],
    ['Russian (Russia) (Female)', 'ru-RU-Standard-A'],
    ['Russian (Russia) (Male)', 'ru-RU-Standard-B'],
    ['Russian (Russia) (Female 2)', 'ru-RU-Standard-C'],
    ['Russian (Russia) (Male 2)', 'ru-RU-Standard-D'],
    ['Arabic (Female)', 'ar-XA-Standard-A'],
    ['Arabic (Male)', 'ar-XA-Standard-B'],
    ['Arabic (Male 2)', 'ar-XA-Standard-C'],
    ['Czech (Czech Republic) (Female)', 'cs-CZ-Standard-A'],
    ['Danish (Denmark) (Female)', 'da-DK-Standard-A'],
    ['Dutch (Netherlands) (Female)', 'nl-NL-Standard-A'],
    ['Dutch (Netherlands) (Male)', 'nl-NL-Standard-B'],
    ['Dutch (Netherlands) (Male 2)', 'nl-NL-Standard-C'],
    ['Dutch (Netherlands) (Female 2)', 'nl-NL-Standard-D'],
    ['Dutch (Netherlands) (Female 3)', 'nl-NL-Standard-E'],
    ['English (Australia) (Female)', 'en-AU-Standard-A'],
    ['English (Australia) (Male)', 'en-AU-Standard-B'],
    ['English (Australia) (Female 2)', 'en-AU-Standard-C'],
    ['English (Australia) (Male 2)', 'en-AU-Standard-D'],
    ['English (India) (Female)', 'en-IN-Standard-A'],
    ['English (India) (Male)', 'en-IN-Standard-B'],
    ['English (India) (Male 2)', 'en-IN-Standard-C'],
    ['English (UK) (Female)', 'en-GB-Standard-A'],
    ['English (UK) (Male)', 'en-GB-Standard-B'],
    ['English (UK) (Female 2)', 'en-GB-Standard-C'],
    ['English (UK) (Male 2)', 'en-GB-Standard-D'],
    ['Filipino (Philippines) (Female)', 'fil-PH-Standard-A'],
    ['Finnish (Finland) (Female)', 'fi-FI-Standard-A'],
    ['French (Canada) (Female)', 'fr-CA-Standard-A'],
    ['French (Canada) (Male)', 'fr-CA-Standard-B'],
    ['French (Canada) (Female 2)', 'fr-CA-Standard-C'],
    ['French (Canada) (Male 2)', 'fr-CA-Standard-D'],
    ['French (France) (Female)', 'fr-FR-Standard-A'],
    ['French (France) (Male)', 'fr-FR-Standard-B'],
    ['French (France) (Female 2)', 'fr-FR-Standard-C'],
    ['French (France) (Male 2)', 'fr-FR-Standard-D'],
    ['Greek (Greece) (Female)', 'el-GR-Standard-A'],
    ['Hindi (India) (Female)', 'hi-IN-Standard-A'],
    ['Hindi (India) (Male)', 'hi-IN-Standard-B'],
    ['Hindi (India) (Male 2)', 'hi-IN-Standard-C'],
    ['Hungarian (Hungary) (Female)', 'hu-HU-Standard-A'],
    ['Indonesian (Indonesia) (Female)', 'id-ID-Standard-A'],
    ['Indonesian (Indonesia) (Male)', 'id-ID-Standard-B'],
    ['Indonesian (Indonesia) (Male 2)', 'id-ID-Standard-C'],
    ['Italian (Italy) (Female)', 'it-IT-Standard-A'],
    ['Italian (Italy) (Female 2)', 'it-IT-Standard-B'],
    ['Italian (Italy) (Male)', 'it-IT-Standard-C'],
    ['Italian (Italy) (Male 2)', 'it-IT-Standard-D'],
    ['Japanese (Japan) (Female)', 'ja-JP-Standard-A'],
    ['Japanese (Japan) (Female 2)', 'ja-JP-Standard-B'],
    ['Japanese (Japan) (Male)', 'ja-JP-Standard-C'],
    ['Japanese (Japan) (Male 2)', 'ja-JP-Standard-D'],
    ['Korean (South Korea) (Female)', 'ko-KR-Standard-A'],
    ['Korean (South Korea) (Female 2)', 'ko-KR-Standard-B'],
    ['Korean (South Korea) (Male)', 'ko-KR-Standard-C'],
    ['Korean (South Korea) (Male 2)', 'ko-KR-Standard-D'],
    ['Mandarin Chinese (Female)', 'cmn-CN-Standard-A'],
    ['Mandarin Chinese (Male)', 'cmn-CN-Standard-B'],
    ['Mandarin Chinese (Male 2)', 'cmn-CN-Standard-C'],
    ['Norwegian (Norway) (Female)', 'nb-NO-Standard-A'],
    ['Norwegian (Norway) (Male)', 'nb-NO-Standard-B'],
    ['Norwegian (Norway) (Female 2)', 'nb-NO-Standard-C'],
    ['Norwegian (Norway) (Male 2)', 'nb-NO-Standard-D'],
    ['Norwegian (Norway) (Female 3)', 'nb-no-Standard-E'],
    ['Polish (Poland) (Female)', 'pl-PL-Standard-A'],
    ['Polish (Poland) (Male)', 'pl-PL-Standard-B'],
    ['Polish (Poland) (Male 2)', 'pl-PL-Standard-C'],
    ['Polish (Poland) (Female 2)', 'pl-PL-Standard-D'],
    ['Polish (Poland) (Female 3)', 'pl-PL-Standard-E'],
    ['Portuguese (Brazil) (Female)', 'pt-BR-Standard-A'],
    ['Portuguese (Portugal) (Female)', 'pt-PT-Standard-A'],
    ['Portuguese (Portugal) (Male)', 'pt-PT-Standard-B'],
    ['Portuguese (Portugal) (Male 2)', 'pt-PT-Standard-C'],
    ['Portuguese (Portugal) (Female 2)', 'pt-PT-Standard-D'],
    ['Slovak (Slovakia) (Female)', 'sk-SK-Standard-A'],
    ['Spanish (Spain) (Female)', 'es-ES-Standard-A'],
    ['Swedish (Sweden) (Female)', 'sv-SE-Standard-A'],
    ['Turkish (Turkey) (Female)', 'tr-TR-Standard-A'],
    ['Turkish (Turkey) (Male)', 'tr-TR-Standard-B'],
    ['Turkish (Turkey) (Female 2)', 'tr-TR-Standard-C'],
    ['Turkish (Turkey) (Female 3)', 'tr-TR-Standard-D'],
    ['Turkish (Turkey) (Male)', 'tr-TR-Standard-E'],
    ['Ukrainian (Ukraine) (Female)', 'uk-UA-Standard-A'],
    ['Vietnamese (Vietnam) (Female)', 'vi-VN-Standard-A'],
    ['Vietnamese (Vietnam) (Male)', 'vi-VN-Standard-B'],
    ['Vietnamese (Vietnam) (Female 2)', 'vi-VN-Standard-C'],
    ['Vietnamese (Vietnam) (Male 2)', 'vi-VN-Standard-D'],
];
